language: java
jdk:
- oraclejdk8
install: true
deploy:
  provider: heroku
  api_key:
    secure: jLIOHPgRscpYkJec/sbKYEAgYd2//07RoSfrcnd0guyQ1ZdcpcpnUCBcsxadwMl4/87m9n7PqEJDlSIfFVOtnBS9H3Vm6RJrQWl5JaPmk6fL/OikLZEYxBbSFVF5Hir6ivZmmPPs5zFvi25Kw3PeCyn7J0vosniEvyF6kKKVtFFPzuYOrxmagK3fC/qGZz4Wt6UKG2chI/IeL6XSxqPK0O9Q1wmxvlxm7T2w0Vuyg/CiekGwrWUOjE9qAH0goasQBWV7Wr4FzHJsQNPv5WUkBlRpDOygDNCmFgQqZbztyjfIPnIOhGwgdrsFNoODlnjxIyKhzRjLxrAoLc3WNH/NTqzYI8ksF9LrYWV7ADTPJ6QcPEM5V1ZPO4l72FRIM+2x/EcDv4V5fbh3KUFAVNdsw3tSB0So60FgxDqxSnZJfgM0CrBkR1GJtV/WxP7YAR/gXPZ9dXwwRDaKHgXa3ZgZSzslLY2wGJiA+je4IUM+4HyqjOu5UN+XAgoq7nDPm5XUp6FzV8Rqy4wsAYKmRjWY2mIBG8+gWFv1EzLWxsGfItcNe6NYwhLM2L4sCBIYQddx+I0CE2UWY1SgKtSv7GJIJpcuXPeoRcPSb4z522AqKNaThrJgvyOX8Ntu5Ez3luIDf1iHnEgjFhxsqPZVQeTFRVzxGv5sZSpkd1ruzC/tJwU=
